### ISSUE TITLE
Barrel in level 3 spawns on x = 0 after spamming reset key

### ISSUE THREAD

**Issue by Darr3n2GG** [Darr3n2GG/Puzzle-Knights-2P-#4]
how to reproduce:
1. skip to level 3
2. spam "P"
3. error occurs with barrel

**Comment by cyb3rgeorge** [comment]
Issue also in level 4

**Comment by cyb3rgeorge** [comment]
I might have a solution

**Comment by cyb3rgeorge** [comment]
https://github.com/Darr3n2GG/Puzzle-Knights-2P-/pull/5 Solved
