### ISSUE TITLE
Floating barrel

### ISSUE THREAD

**Issue by Bryan-CoderS** [Darr3n2GG/Puzzle-Knights-2P-#7]
The barrel remains in air even the platform is lowered.

**Comment by Darr3n2GG** [comment]
At Level 4 right?

**Comment by Bryan-CoderS** [comment]
Yea, the barrel is floating. However, it falls normally when player steps on it

**Comment by Darr3n2GG** [comment]
fixed in https://github.com/Darr3n2GG/Puzzle-Knights-2P-/commit/1f05fa1eb2c52c9c9dcc5a6d014baffb92bac569
